version: '2'

services:
  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    restart: always
    ports:
      - "4160:4160"
      - "4161:4161"
    command: "/nsqlookupd"

  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    restart: always
    ports:
      - "4150:4150"
      - "4151:4151"
    command: "/nsqd --broadcast-address=192.168.99.100 --lookupd-tcp-address=192.168.99.100:4160"  
